### ISSUE TITLE
Invisible chunks in Freecam

### ISSUE THREAD

**Issue by FriedrichM** [kami-blue/client#1663]
When you fly far away in freecam chunks disappear and stay invisible even when you return to the Playerpostion.

**Comment by FriedrichM** [comment]
this has been bugging me for a long time. i might look into fixing it later

**Comment by Doogie13** [comment]
might be to do with some rendering things to make game run smoother (try using freecam in a 2x1 box it will show like 1 or 2 chunks max)

**Comment by l1ving** [comment]
This should already be fixed. Please provide a screenshot of `;tsc`

**Comment by FriedrichM** [comment]
i just tried on the master with only freecam on and all chunks disappear if you are more than one chunk away from the last loaded chunk. if you fly further the chunks that are then further away from the freecam position than your render distance will be gone upon returning aswell.

**Comment by l1ving** [comment]
Is this on a server?

**Comment by FriedrichM** [comment]
happens both in sp and on 2b2t.dev

**Comment by FriedrichM** [comment]
i messed something up in my pull maybe i was on the wrong remote sorry . anyways the first part is no longer happening.
the last one still happens:

> if you fly further the chunks that are then further away from the freecam position than your render distance will be gone upon returning

**Comment by FriedrichM** [comment]
i have found the source of the problem and i am working on a fix.

**Comment by Xiaro** [comment]
Closed by #1759
